# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6773c393c4df6b419c928d93b3b8696f887778ab97b44c14334f16514ac614c6db29b28c142ce14d87c727d0655a914b6b0f5e6351a51dd7915ec5ef6e1e308

test:
  secret_key_base: e46584d846fe5ecb29f406ee02d807def339988094cebebaded786cdb533ed4bf88e5815edb6fd8233d8330ad72ac36de532f364cb92924452fe6bfdad8dd818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
